apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: adsskipredictor-transform
  labels:
    cloud.googleapis.com/location: europe-west6
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: [REPLACE_WITH_YOUR_DB]
        run.googleapis.com/execution-environment: gen2
    spec:
      taskCount: 1
      template:
        spec:
          timeoutSeconds: 600
          maxRetries: 3
          containers:
          - image: [REPLACE_WITH_YOUR_IMAGE]
            env:
            - name: WEATHER_PATH
              value: /mnt/weather
            - name: PRICES_PATH
              value: /mnt/prices
            - name: SENTRY_DSN
              value: [REPLACE_WITH_YOUR_SENTRY_DSN]
            - name: SENTRY_PROFILE_RATE
              value: "0.1"
            - name: SENTRY_TRACES_RATE
              value: "0.1"
            - name: DB_USER
              value: [REPLACE_WITH_YOUR_USER]
            - name: DB_PASS
              value: [REPLACE_WITH_YOUR_PASS]
            - name: DB_NAME
              value: [REPLACE_WITH_YOUR_DB]
            - name: DB_HOST
              value: [REPLACE_WITH_YOUR_DB_HOST]
            volumeMounts:
            - mountPath: /mnt/prices
              name: prices
            - mountPath: /mnt/weather
              name: weather
            resources:
              limits:
                cpu: 2000m
                memory: 1Gi
          volumes:
          - name: weather
            csi:
              driver: gcsfuse.run.googleapis.com
              readOnly: true
              volumeAttributes:
                bucketName: adsskipredictor_weather
          - name: prices
            csi:
              driver: gcsfuse.run.googleapis.com
              readOnly: true
              volumeAttributes:
                bucketName: adsskipredictor