steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/scraper:$COMMIT_SHA', './scraper' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/scraper:$COMMIT_SHA' ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/transform:$COMMIT_SHA', './transform' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/transform:$COMMIT_SHA' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/weather:$COMMIT_SHA', './weather' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/weather:$COMMIT_SHA' ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'jobs'
  - 'update'
  - 'adsskipredictor-scraper'
  - '--image'
  - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/scraper:$COMMIT_SHA
  - '--project'
  - '$PROJECT_ID'
  - '--region'
  - '${_LOCATION}'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'jobs'
  - 'update'
  - 'adsskipredictor-transform'
  - '--image'
  - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/transform:$COMMIT_SHA
  - '--project'
  - '$PROJECT_ID'
  - '--region'
  - '${_LOCATION}'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'jobs'
  - 'update'
  - 'adsskipredictor-weather'
  - '--image'
  - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/weather:$COMMIT_SHA
  - '--project'
  - '$PROJECT_ID'
  - '--region'
  - '${_LOCATION}'
images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/scraper:$COMMIT_SHA'
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/transform:$COMMIT_SHA'
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/weather:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
